filter:
    paths: [src/*]
    excluded_paths: [vendor/*, tests/*, examples/*, templates/*]

before_commands:
    - "composer install --dev"

tools:
    php_analyzer: true
    external_code_coverage: true
    php_mess_detector: true
    php_code_sniffer: true
    sensiolabs_security_checker: true
    php_code_coverage: true
    php_pdepend: true
    php_loc:
        enabled: true
        excluded_dirs: [vendor, tests, examples, templates]
    php_cpd:
        enabled: true
        excluded_dirs: [vendor, tests, examples, templates]